### ISSUE TITLE
Minor test failure as underlying H5py library changed an exception from KeyError to TypeError

### ISSUE THREAD

**Issue by bnlawrence** [h5netcdf/h5netcdf#236]
#### What happened:

The test suite raised two errors

#### What you expected to happen:

No errors

#### Context:

Python 3.11.8
H5py 3.11.0
h5netcdf version 999 ??  (actually latest main)

#### Available Fix

There is an [available fix](https://github.com/bnlawrence/h5netcdf/commit/4d5477edb972aaa9f3b0931d6ed3f9576a7b80f7) in the main branch of my fork. I haven't done a pull request, because I don't know when and how the behaviour changed in the underlying library and/or python.

**Comment by kmuehlbauer** [comment]
Thanks @bnlawrence for raising this and sorry for the delay. This isn't raised in the current testsuite. Is this still an issue for you or can you give more details on your failing environment?

**Comment by kmuehlbauer** [comment]
we are testing:

```
      matrix:
        python-version: ["3.10", "3.12"]
        h5py-version: ["3.10", "3.11"]
        numpy-version: ["1"]
```
```
      matrix:
        python-version: ["3.11", "3.12"]
        h5py-version: ["3.11"]
        numpy-version: ["2"]
```
